
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov 19 2025 11:56:33 IST (Nov 19 2025 06:26:33 UTC)

// Verification Directory fv/mult4x4_pipelined 

module mult4x4_pipelined(clk, rst_n, A, B, P);
  input clk, rst_n;
  input [3:0] A, B;
  output [7:0] P;
  wire clk, rst_n;
  wire [3:0] A, B;
  wire [7:0] P;
  wire [7:0] s1_b;
  wire [5:0] s1_a;
  wire [3:0] pp3;
  wire [3:0] pp1;
  wire [3:0] pp0;
  wire [3:0] pp2;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_38;
  wire n_39, n_40, n_42, n_43, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_58, n_60;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_107, n_118;
  wire n_129, n_140, n_151, n_162, n_173, n_184, n_195, n_206;
  wire n_217, n_228, n_239, n_242, n_253, n_264, n_278, n_281;
  wire n_289, n_300, n_311, n_322, n_421, n_425, n_433, n_437;
  wire n_441, n_445, n_450, n_451, n_452;
  DFFRX4 \P_reg[7] (.RN (rst_n), .CK (clk), .D (n_91), .Q (P[7]), .QN
       (UNCONNECTED));
  DFFRX4 \P_reg[6] (.RN (rst_n), .CK (clk), .D (n_90), .Q (P[6]), .QN
       (UNCONNECTED0));
  XNOR2X1 g1126__2398(.A (n_107), .B (s1_b[7]), .Y (n_91));
  INVX1 g1128(.A (n_242), .Y (n_90));
  NAND2X1 g1129__5107(.A (n_107), .B (n_87), .Y (n_89));
  OR2X2 g1131__6260(.A (n_129), .B (n_118), .Y (n_87));
  NAND2X2 g1132__4319(.A (n_129), .B (n_118), .Y (n_88));
  DFFRX4 \P_reg[5] (.RN (rst_n), .CK (clk), .D (n_85), .Q (P[5]), .QN
       (UNCONNECTED1));
  OR2X2 g1133__8428(.A (n_84), .B (n_73), .Y (n_86));
  XNOR2X1 g1134__5526(.A (n_83), .B (n_74), .Y (n_85));
  DFFRX4 \P_reg[4] (.RN (rst_n), .CK (clk), .D (n_82), .Q (P[4]), .QN
       (UNCONNECTED2));
  AND2X2 g1136__6783(.A (n_83), .B (n_72), .Y (n_84));
  XNOR2X1 g1138__3680(.A (n_80), .B (n_79), .Y (n_82));
  OR2X2 g1137__1617(.A (n_81), .B (n_78), .Y (n_83));
  AND2X2 g1140__2802(.A (n_300), .B (n_77), .Y (n_81));
  DFFRX4 \P_reg[3] (.RN (rst_n), .CK (clk), .D (n_75), .Q (P[3]), .QN
       (UNCONNECTED3));
  OR2X2 g1141__1705(.A (n_78), .B (n_76), .Y (n_79));
  INVX1 g1143(.A (n_76), .Y (n_77));
  XOR2X1 g1147__5122(.A (n_55), .B (n_70), .Y (n_75));
  OR2X2 g1142__8246(.A (n_73), .B (n_71), .Y (n_74));
  AND2X2 g1144__7098(.A (s1_b[4]), .B (s1_a[4]), .Y (n_78));
  NOR2X4 g1145__6131(.A (s1_b[4]), .B (s1_a[4]), .Y (n_76));
  AND2X2 g1154__1881(.A (n_281), .B (n_162), .Y (n_80));
  INVX1 g1146(.A (n_71), .Y (n_72));
  NOR2X4 g1149__5115(.A (s1_a[5]), .B (s1_b[5]), .Y (n_71));
  DFFRX4 \s1_a_reg[4] (.RN (rst_n), .CK (clk), .D (n_63), .Q (s1_a[4]),
       .QN (UNCONNECTED4));
  NAND2X2 g1156__7482(.A (n_162), .B (n_67), .Y (n_70));
  DFFRX1 \s1_b_reg[6] (.RN (rst_n), .CK (clk), .D (n_65), .Q (s1_b[6]),
       .QN (UNCONNECTED5));
  AND2X2 g1148__4733(.A (s1_a[5]), .B (s1_b[5]), .Y (n_73));
  NAND2X1 g1155__6161(.A (n_55), .B (n_66), .Y (n_68));
  DFFRX4 \P_reg[2] (.RN (rst_n), .CK (clk), .D (n_452), .Q (P[2]), .QN
       (UNCONNECTED6));
  DFFSRX2 \s1_b_reg[7] (.RN (rst_n), .SN (1'b1), .CK (clk), .D (n_64),
       .Q (s1_b[7]), .QN (UNCONNECTED7));
  DFFRX4 \s1_a_reg[5] (.RN (rst_n), .CK (clk), .D (n_62), .Q (s1_a[5]),
       .QN (UNCONNECTED8));
  BUFX2 g1159(.A (n_289), .Y (n_67));
  AOI2BB1X2 g1160__9315(.A0N (n_437), .A1N (n_433), .B0 (n_64), .Y
       (n_65));
  AOI2BB1X2 g1161__9945(.A0N (n_445), .A1N (n_425), .B0 (n_62), .Y
       (n_63));
  OR2X2 g1158__2883(.A (n_140), .B (n_151), .Y (n_69));
  NAND2X2 g1162__2346(.A (n_421), .B (n_140), .Y (n_66));
  AND2X4 g1167__1666(.A (n_60), .B (pp3[3]), .Y (n_64));
  AND2X4 g1168__6417(.A (n_58), .B (pp1[3]), .Y (n_62));
  DFFRX1 \s1_a_reg[3] (.RN (rst_n), .CK (clk), .D (n_53), .Q (s1_a[3]),
       .QN (UNCONNECTED9));
  DFFRX4 \s1_b_reg[5] (.RN (rst_n), .CK (clk), .D (n_51), .Q (s1_b[5]),
       .QN (UNCONNECTED10));
  OR2X2 g1177__5477(.A (n_48), .B (n_28), .Y (n_58));
  CLKINVX3 g1170(.A (n_54), .Y (n_55));
  OR2X2 g1173__2398(.A (n_50), .B (n_33), .Y (n_60));
  XNOR2X1 g1176__5107(.A (n_47), .B (n_29), .Y (n_53));
  DFFRX4 \s1_b_reg[4] (.RN (rst_n), .CK (clk), .D (n_46), .Q (s1_b[4]),
       .QN (UNCONNECTED11));
  OR2X2 g1172__6260(.A (n_239), .B (n_195), .Y (n_52));
  XNOR2X1 g1175__4319(.A (n_49), .B (n_34), .Y (n_51));
  AND2X4 g1174__8428(.A (s1_b[2]), .B (s1_a[2]), .Y (n_54));
  AND2X2 g1180__5526(.A (n_49), .B (n_21), .Y (n_50));
  AND2X2 g1181__6783(.A (n_47), .B (n_24), .Y (n_48));
  XOR2X1 g1184__3680(.A (n_35), .B (n_40), .Y (n_46));
  SDFFSRX2 \s1_a_reg[2] (.RN (rst_n), .SN (1'b1), .CK (clk), .D (n_27),
       .SI (n_42), .SE (n_31), .Q (s1_a[2]), .QN (UNCONNECTED12));
  DFFRX4 \P_reg[1] (.RN (rst_n), .CK (clk), .D (s1_a[1]), .Q (P[1]),
       .QN (UNCONNECTED13));
  DFFRX1 \s1_b_reg[3] (.RN (rst_n), .CK (clk), .D (n_450), .Q
       (s1_b[3]), .QN (UNCONNECTED14));
  OR2X2 g1183__1617(.A (n_451), .B (n_39), .Y (n_49));
  OR2X2 g1185__2802(.A (n_43), .B (n_30), .Y (n_47));
  DFFRX1 \s1_a_reg[1] (.RN (rst_n), .CK (clk), .D (n_32), .Q (s1_a[1]),
       .QN (UNCONNECTED15));
  AND2X2 g1188__1705(.A (n_26), .B (n_42), .Y (n_43));
  OR2X2 g1194__8246(.A (n_39), .B (n_38), .Y (n_40));
  DFFRX4 \P_reg[0] (.RN (rst_n), .CK (clk), .D (s1_a[0]), .Q (P[0]),
       .QN (UNCONNECTED16));
  OR2X2 g1195__6131(.A (n_33), .B (n_20), .Y (n_34));
  AOI2BB1X2 g1196__1881(.A0N (n_441), .A1N (n_278), .B0 (n_42), .Y
       (n_32));
  OR2X2 g1198__5115(.A (n_30), .B (n_25), .Y (n_31));
  OR2X2 g1199__7482(.A (n_28), .B (n_23), .Y (n_29));
  INVXL g1192(.A (n_42), .Y (n_27));
  INVX1 g1200(.A (n_25), .Y (n_26));
  INVX1 g1207(.A (n_23), .Y (n_24));
  INVX1 g1208(.A (n_20), .Y (n_21));
  AND2X4 g1214__4733(.A (n_17), .B (n_16), .Y (n_38));
  INVX2 g1209(.A (n_19), .Y (n_35));
  DFFRX1 \s1_a_reg[0] (.RN (rst_n), .CK (clk), .D (pp0[0]), .Q
       (s1_a[0]), .QN (UNCONNECTED17));
  OR2X2 g1202__6161(.A (n_311), .B (n_322), .Y (n_18));
  AND2X2 g1204__9315(.A (pp3[2]), .B (pp2[3]), .Y (n_33));
  AND2X2 g1203__9945(.A (pp1[2]), .B (pp0[3]), .Y (n_28));
  NOR2X4 g1205__2883(.A (pp1[1]), .B (pp0[2]), .Y (n_25));
  DFFSRX2 \s1_b_reg[2] (.RN (rst_n), .SN (1'b1), .CK (clk), .D
       (pp2[0]), .Q (s1_b[2]), .QN (UNCONNECTED18));
  NOR2X4 g1211__2346(.A (pp1[2]), .B (pp0[3]), .Y (n_23));
  AND2X2 g1212__1666(.A (pp1[1]), .B (pp0[2]), .Y (n_30));
  AND2X2 g1213__7410(.A (n_184), .B (n_173), .Y (n_39));
  NOR2X4 g1215__6417(.A (pp3[2]), .B (pp2[3]), .Y (n_20));
  AND2X4 g1216__5477(.A (pp3[0]), .B (pp2[1]), .Y (n_19));
  AND2X4 g1217__2398(.A (pp1[0]), .B (pp0[1]), .Y (n_42));
  INVX2 g1218(.A (n_173), .Y (n_17));
  INVX2 g1227(.A (n_184), .Y (n_16));
  DFFRXL \pp2_reg[0] (.RN (rst_n), .CK (clk), .D (n_2), .Q (pp2[0]),
       .QN (UNCONNECTED19));
  DFFRX2 \pp2_reg[1] (.RN (rst_n), .CK (clk), .D (n_7), .Q (pp2[1]),
       .QN (UNCONNECTED20));
  DFFRX2 \pp3_reg[0] (.RN (rst_n), .CK (clk), .D (n_11), .Q (pp3[0]),
       .QN (UNCONNECTED21));
  DFFSRX2 \pp3_reg[1] (.RN (rst_n), .SN (1'b1), .CK (clk), .D (n_5), .Q
       (pp3[1]), .QN (UNCONNECTED22));
  DFFRX2 \pp3_reg[3] (.RN (rst_n), .CK (clk), .D (n_1), .Q (pp3[3]),
       .QN (UNCONNECTED23));
  DFFRX4 \pp1_reg[2] (.RN (rst_n), .CK (clk), .D (n_0), .Q (pp1[2]),
       .QN (UNCONNECTED24));
  DFFRX2 \pp0_reg[1] (.RN (rst_n), .CK (clk), .D (n_10), .Q (pp0[1]),
       .QN (UNCONNECTED25));
  DFFRX4 \pp3_reg[2] (.RN (rst_n), .CK (clk), .D (n_3), .Q (pp3[2]),
       .QN (UNCONNECTED26));
  DFFRXL \pp0_reg[0] (.RN (rst_n), .CK (clk), .D (n_15), .Q (pp0[0]),
       .QN (UNCONNECTED27));
  DFFRX2 \pp1_reg[0] (.RN (rst_n), .CK (clk), .D (n_9), .Q (pp1[0]),
       .QN (UNCONNECTED28));
  DFFSRX2 \pp2_reg[2] (.RN (rst_n), .SN (1'b1), .CK (clk), .D (n_4), .Q
       (pp2[2]), .QN (UNCONNECTED29));
  DFFRX4 \pp0_reg[3] (.RN (rst_n), .CK (clk), .D (n_8), .Q (pp0[3]),
       .QN (UNCONNECTED30));
  DFFRX4 \pp0_reg[2] (.RN (rst_n), .CK (clk), .D (n_12), .Q (pp0[2]),
       .QN (UNCONNECTED31));
  DFFRX2 \pp1_reg[3] (.RN (rst_n), .CK (clk), .D (n_6), .Q (pp1[3]),
       .QN (UNCONNECTED32));
  DFFRX4 \pp1_reg[1] (.RN (rst_n), .CK (clk), .D (n_14), .Q (pp1[1]),
       .QN (UNCONNECTED33));
  DFFRX4 \pp2_reg[3] (.RN (rst_n), .CK (clk), .D (n_13), .Q (pp2[3]),
       .QN (UNCONNECTED34));
  AND2X2 g1239__5107(.A (A[0]), .B (B[0]), .Y (n_15));
  AND2X2 g1236__6260(.A (A[1]), .B (B[1]), .Y (n_14));
  AND2X2 g1237__4319(.A (A[3]), .B (B[2]), .Y (n_13));
  AND2X2 g1238__8428(.A (A[2]), .B (B[0]), .Y (n_12));
  AND2X2 g1246__5526(.A (A[0]), .B (B[3]), .Y (n_11));
  AND2X2 g1240__6783(.A (A[1]), .B (B[0]), .Y (n_10));
  AND2X2 g1241__3680(.A (A[0]), .B (B[1]), .Y (n_9));
  AND2X2 g1242__1617(.A (A[3]), .B (B[0]), .Y (n_8));
  AND2X2 g1248__2802(.A (A[1]), .B (B[2]), .Y (n_7));
  AND2X2 g1244__1705(.A (A[3]), .B (B[1]), .Y (n_6));
  AND2X2 g1245__5122(.A (A[1]), .B (B[3]), .Y (n_5));
  AND2X2 g1247__8246(.A (A[2]), .B (B[2]), .Y (n_4));
  AND2X2 g1243__7098(.A (A[2]), .B (B[3]), .Y (n_3));
  AND2X2 g1249__6131(.A (A[0]), .B (B[2]), .Y (n_2));
  AND2X2 g1251__1881(.A (A[3]), .B (B[3]), .Y (n_1));
  AND2X2 g1250__5115(.A (A[2]), .B (B[1]), .Y (n_0));
  CLKBUFXL drc_bufs1332(.A (n_421), .Y (n_151));
  CLKBUFXL drc_bufs1372(.A (s1_b[2]), .Y (n_195));
  CLKBUFXL drc_bufs1382(.A (pp3[3]), .Y (n_206));
  CLKBUFXL drc_bufs1392(.A (pp1[3]), .Y (n_217));
  CLKBUFXL drc_bufs1402(.A (pp0[1]), .Y (n_228));
  CLKBUFXL drc_bufs1412(.A (s1_a[2]), .Y (n_239));
  CLKBUFXL drc_bufs(.A (n_89), .Y (n_242));
  CLKBUFXL drc_bufs1425(.A (n_60), .Y (n_253));
  CLKBUFXL drc_bufs1436(.A (n_58), .Y (n_264));
  BUFX2 drc_bufs1450(.A (pp1[0]), .Y (n_278));
  CLKBUFXL drc_bufs1453(.A (n_68), .Y (n_281));
  CLKBUFXL drc_bufs1461(.A (n_66), .Y (n_289));
  CLKBUFXL drc_bufs1472(.A (n_80), .Y (n_300));
  CLKBUFXL drc_bufs1483(.A (pp2[1]), .Y (n_311));
  CLKBUFXL drc_bufs1494(.A (pp3[0]), .Y (n_322));
  BUFX2 fopt(.A (n_88), .Y (n_107));
  CLKBUFX3 drc(.A (s1_a[3]), .Y (n_140));
  CLKBUFX3 drc1530(.A (s1_b[6]), .Y (n_118));
  BUFX3 drc1542(.A (n_69), .Y (n_162));
  BUFX3 drc1554(.A (n_86), .Y (n_129));
  BUFX3 drc1566(.A (pp3[1]), .Y (n_184));
  BUFX3 drc1578(.A (pp2[2]), .Y (n_173));
  BUFX2 drc1590(.A (s1_b[3]), .Y (n_421));
  CLKBUFX1 drc1594(.A (n_217), .Y (n_425));
  CLKBUFX1 drc1602(.A (n_206), .Y (n_433));
  CLKBUFX1 drc1606(.A (n_253), .Y (n_437));
  CLKBUFX1 drc1610(.A (n_228), .Y (n_441));
  CLKBUFX1 drc1614(.A (n_264), .Y (n_445));
  AND2X2 g2(.A (n_18), .B (n_35), .Y (n_450));
  NOR2BX2 g1619(.AN (n_19), .B (n_38), .Y (n_451));
  AND2X2 g1620(.A (n_52), .B (n_55), .Y (n_452));
endmodule

