/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadenceserver.rvce.in)
#  Generated on:      Wed Nov 19 13:25:21 2025
#  Design:            mult4x4_pipelined
#  Command:           saveNetlist mult4x4_pipelined_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov 19 2025 11:56:33 IST (Nov 19 2025 06:26:33 UTC)
// Verification Directory fv/mult4x4_pipelined 
module mult4x4_pipelined (
	clk, 
	rst_n, 
	A, 
	B, 
	P);
   input clk;
   input rst_n;
   input [3:0] A;
   input [3:0] B;
   output [7:0] P;

   // Internal wires
   wire FE_PHN7_s1_a_1;
   wire FE_PHN6_pp0_0;
   wire FE_PHN5_pp1_3;
   wire FE_PHN4_pp2_0;
   wire FE_PHN3_s1_a_0;
   wire FE_PHN2_s1_a_1;
   wire FE_OFN1_s1_a_3;
   wire FE_OFN0_s1_b_6;
   wire [7:0] s1_b;
   wire [5:0] s1_a;
   wire [3:0] pp3;
   wire [3:0] pp1;
   wire [3:0] pp0;
   wire [3:0] pp2;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire UNCONNECTED25;
   wire UNCONNECTED26;
   wire UNCONNECTED27;
   wire UNCONNECTED28;
   wire UNCONNECTED29;
   wire UNCONNECTED30;
   wire UNCONNECTED31;
   wire UNCONNECTED32;
   wire UNCONNECTED33;
   wire UNCONNECTED34;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_42;
   wire n_43;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_58;
   wire n_60;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_151;
   wire n_195;
   wire n_206;
   wire n_217;
   wire n_228;
   wire n_239;
   wire n_242;
   wire n_253;
   wire n_264;
   wire n_281;
   wire n_289;
   wire n_300;
   wire n_311;
   wire n_322;
   wire n_425;
   wire n_433;
   wire n_437;
   wire n_441;
   wire n_445;
   wire n_450;
   wire n_451;
   wire n_452;

   BUFX2 FE_PHC7_s1_a_1 (.A(FE_PHN2_s1_a_1),
	.Y(FE_PHN7_s1_a_1));
   BUFX2 FE_PHC6_pp0_0 (.A(pp0[0]),
	.Y(FE_PHN6_pp0_0));
   BUFX2 FE_PHC5_pp1_3 (.A(pp1[3]),
	.Y(FE_PHN5_pp1_3));
   DLY2X1 FE_PHC4_pp2_0 (.A(pp2[0]),
	.Y(FE_PHN4_pp2_0));
   DLY1X1 FE_PHC3_s1_a_0 (.A(s1_a[0]),
	.Y(FE_PHN3_s1_a_0));
   BUFX2 FE_PHC2_s1_a_1 (.A(s1_a[1]),
	.Y(FE_PHN2_s1_a_1));
   BUFX2 FE_OFC1_s1_a_3 (.A(s1_a[3]),
	.Y(FE_OFN1_s1_a_3));
   BUFX2 FE_OFC0_s1_b_6 (.A(s1_b[6]),
	.Y(FE_OFN0_s1_b_6));
   DFFRX4 \P_reg[7]  (.CK(clk),
	.D(n_91),
	.Q(P[7]),
	.QN(UNCONNECTED),
	.RN(rst_n));
   DFFRX4 \P_reg[6]  (.CK(clk),
	.D(n_90),
	.Q(P[6]),
	.QN(UNCONNECTED0),
	.RN(rst_n));
   XNOR2X1 g1126__2398 (.A(n_88),
	.B(s1_b[7]),
	.Y(n_91));
   INVX1 g1128 (.A(n_242),
	.Y(n_90));
   NAND2X1 g1129__5107 (.A(n_88),
	.B(n_87),
	.Y(n_89));
   OR2X2 g1131__6260 (.A(n_86),
	.B(FE_OFN0_s1_b_6),
	.Y(n_87));
   NAND2X2 g1132__4319 (.A(n_86),
	.B(FE_OFN0_s1_b_6),
	.Y(n_88));
   DFFRX4 \P_reg[5]  (.CK(clk),
	.D(n_85),
	.Q(P[5]),
	.QN(UNCONNECTED1),
	.RN(rst_n));
   OR2X1 g1133__8428 (.A(n_84),
	.B(n_73),
	.Y(n_86));
   XNOR2X1 g1134__5526 (.A(n_83),
	.B(n_74),
	.Y(n_85));
   DFFRX4 \P_reg[4]  (.CK(clk),
	.D(n_82),
	.Q(P[4]),
	.QN(UNCONNECTED2),
	.RN(rst_n));
   AND2X1 g1136__6783 (.A(n_83),
	.B(n_72),
	.Y(n_84));
   XNOR2X1 g1138__3680 (.A(n_80),
	.B(n_79),
	.Y(n_82));
   OR2X1 g1137__1617 (.A(n_81),
	.B(n_78),
	.Y(n_83));
   AND2X1 g1140__2802 (.A(n_300),
	.B(n_77),
	.Y(n_81));
   DFFRX4 \P_reg[3]  (.CK(clk),
	.D(n_75),
	.Q(P[3]),
	.QN(UNCONNECTED3),
	.RN(rst_n));
   OR2X1 g1141__1705 (.A(n_78),
	.B(n_76),
	.Y(n_79));
   INVX1 g1143 (.A(n_76),
	.Y(n_77));
   XOR2X1 g1147__5122 (.A(n_55),
	.B(n_70),
	.Y(n_75));
   OR2X1 g1142__8246 (.A(n_73),
	.B(n_71),
	.Y(n_74));
   AND2X1 g1144__7098 (.A(s1_b[4]),
	.B(s1_a[4]),
	.Y(n_78));
   NOR2X2 g1145__6131 (.A(s1_b[4]),
	.B(s1_a[4]),
	.Y(n_76));
   AND2X1 g1154__1881 (.A(n_281),
	.B(n_69),
	.Y(n_80));
   INVX1 g1146 (.A(n_71),
	.Y(n_72));
   NOR2X2 g1149__5115 (.A(s1_a[5]),
	.B(s1_b[5]),
	.Y(n_71));
   DFFRX2 \s1_a_reg[4]  (.CK(clk),
	.D(n_63),
	.Q(s1_a[4]),
	.QN(UNCONNECTED4),
	.RN(rst_n));
   NAND2X2 g1156__7482 (.A(n_69),
	.B(n_289),
	.Y(n_70));
   DFFRX1 \s1_b_reg[6]  (.CK(clk),
	.D(n_65),
	.Q(s1_b[6]),
	.QN(UNCONNECTED5),
	.RN(rst_n));
   AND2X1 g1148__4733 (.A(s1_a[5]),
	.B(s1_b[5]),
	.Y(n_73));
   NAND2X1 g1155__6161 (.A(n_55),
	.B(n_66),
	.Y(n_68));
   DFFRX4 \P_reg[2]  (.CK(clk),
	.D(n_452),
	.Q(P[2]),
	.QN(UNCONNECTED6),
	.RN(rst_n));
   DFFSRX1 \s1_b_reg[7]  (.CK(clk),
	.D(n_64),
	.Q(s1_b[7]),
	.QN(UNCONNECTED7),
	.RN(rst_n),
	.SN(1'b1));
   DFFRX2 \s1_a_reg[5]  (.CK(clk),
	.D(n_62),
	.Q(s1_a[5]),
	.QN(UNCONNECTED8),
	.RN(rst_n));
   AOI2BB1X1 g1160__9315 (.A0N(n_437),
	.A1N(n_433),
	.B0(n_64),
	.Y(n_65));
   AOI2BB1X1 g1161__9945 (.A0N(n_445),
	.A1N(n_425),
	.B0(n_62),
	.Y(n_63));
   OR2X2 g1158__2883 (.A(FE_OFN1_s1_a_3),
	.B(n_151),
	.Y(n_69));
   NAND2X2 g1162__2346 (.A(s1_b[3]),
	.B(FE_OFN1_s1_a_3),
	.Y(n_66));
   AND2X1 g1167__1666 (.A(n_60),
	.B(pp3[3]),
	.Y(n_64));
   AND2X1 g1168__6417 (.A(n_58),
	.B(FE_PHN5_pp1_3),
	.Y(n_62));
   DFFRX1 \s1_a_reg[3]  (.CK(clk),
	.D(n_53),
	.Q(s1_a[3]),
	.QN(UNCONNECTED9),
	.RN(rst_n));
   DFFRX2 \s1_b_reg[5]  (.CK(clk),
	.D(n_51),
	.Q(s1_b[5]),
	.QN(UNCONNECTED10),
	.RN(rst_n));
   OR2X1 g1177__5477 (.A(n_48),
	.B(n_28),
	.Y(n_58));
   INVX1 g1170 (.A(n_54),
	.Y(n_55));
   OR2X1 g1173__2398 (.A(n_50),
	.B(n_33),
	.Y(n_60));
   XNOR2X1 g1176__5107 (.A(n_47),
	.B(n_29),
	.Y(n_53));
   DFFRX2 \s1_b_reg[4]  (.CK(clk),
	.D(n_46),
	.Q(s1_b[4]),
	.QN(UNCONNECTED11),
	.RN(rst_n));
   OR2X1 g1172__6260 (.A(n_239),
	.B(n_195),
	.Y(n_52));
   XNOR2X1 g1175__4319 (.A(n_49),
	.B(n_34),
	.Y(n_51));
   AND2X1 g1174__8428 (.A(s1_b[2]),
	.B(s1_a[2]),
	.Y(n_54));
   AND2X1 g1180__5526 (.A(n_49),
	.B(n_21),
	.Y(n_50));
   AND2X1 g1181__6783 (.A(n_47),
	.B(n_24),
	.Y(n_48));
   XOR2X1 g1184__3680 (.A(n_35),
	.B(n_40),
	.Y(n_46));
   SDFFSRX1 \s1_a_reg[2]  (.CK(clk),
	.D(n_27),
	.Q(s1_a[2]),
	.QN(UNCONNECTED12),
	.RN(rst_n),
	.SE(n_31),
	.SI(n_42),
	.SN(1'b1));
   DFFRX4 \P_reg[1]  (.CK(clk),
	.D(FE_PHN7_s1_a_1),
	.Q(P[1]),
	.QN(UNCONNECTED13),
	.RN(rst_n));
   DFFRX1 \s1_b_reg[3]  (.CK(clk),
	.D(n_450),
	.Q(s1_b[3]),
	.QN(UNCONNECTED14),
	.RN(rst_n));
   OR2X1 g1183__1617 (.A(n_451),
	.B(n_39),
	.Y(n_49));
   OR2X1 g1185__2802 (.A(n_43),
	.B(n_30),
	.Y(n_47));
   DFFRX1 \s1_a_reg[1]  (.CK(clk),
	.D(n_32),
	.Q(s1_a[1]),
	.QN(UNCONNECTED15),
	.RN(rst_n));
   AND2X1 g1188__1705 (.A(n_26),
	.B(n_42),
	.Y(n_43));
   OR2X1 g1194__8246 (.A(n_39),
	.B(n_38),
	.Y(n_40));
   DFFRX4 \P_reg[0]  (.CK(clk),
	.D(FE_PHN3_s1_a_0),
	.Q(P[0]),
	.QN(UNCONNECTED16),
	.RN(rst_n));
   OR2X1 g1195__6131 (.A(n_33),
	.B(n_20),
	.Y(n_34));
   AOI2BB1X1 g1196__1881 (.A0N(n_441),
	.A1N(pp1[0]),
	.B0(n_42),
	.Y(n_32));
   OR2X1 g1198__5115 (.A(n_30),
	.B(n_25),
	.Y(n_31));
   OR2X1 g1199__7482 (.A(n_28),
	.B(n_23),
	.Y(n_29));
   INVXL g1192 (.A(n_42),
	.Y(n_27));
   INVX1 g1200 (.A(n_25),
	.Y(n_26));
   INVX1 g1207 (.A(n_23),
	.Y(n_24));
   INVX1 g1208 (.A(n_20),
	.Y(n_21));
   AND2X1 g1214__4733 (.A(n_17),
	.B(n_16),
	.Y(n_38));
   INVX1 g1209 (.A(n_19),
	.Y(n_35));
   DFFRXL \s1_a_reg[0]  (.CK(clk),
	.D(FE_PHN6_pp0_0),
	.Q(s1_a[0]),
	.QN(UNCONNECTED17),
	.RN(rst_n));
   OR2X1 g1202__6161 (.A(n_311),
	.B(n_322),
	.Y(n_18));
   AND2X1 g1204__9315 (.A(pp3[2]),
	.B(pp2[3]),
	.Y(n_33));
   AND2X1 g1203__9945 (.A(pp1[2]),
	.B(pp0[3]),
	.Y(n_28));
   NOR2X2 g1205__2883 (.A(pp1[1]),
	.B(pp0[2]),
	.Y(n_25));
   DFFSRX1 \s1_b_reg[2]  (.CK(clk),
	.D(FE_PHN4_pp2_0),
	.Q(s1_b[2]),
	.QN(UNCONNECTED18),
	.RN(rst_n),
	.SN(1'b1));
   NOR2X2 g1211__2346 (.A(pp1[2]),
	.B(pp0[3]),
	.Y(n_23));
   AND2X1 g1212__1666 (.A(pp1[1]),
	.B(pp0[2]),
	.Y(n_30));
   AND2X1 g1213__7410 (.A(pp3[1]),
	.B(pp2[2]),
	.Y(n_39));
   NOR2X2 g1215__6417 (.A(pp3[2]),
	.B(pp2[3]),
	.Y(n_20));
   AND2X1 g1216__5477 (.A(pp3[0]),
	.B(pp2[1]),
	.Y(n_19));
   AND2X1 g1217__2398 (.A(pp1[0]),
	.B(pp0[1]),
	.Y(n_42));
   INVX1 g1218 (.A(pp2[2]),
	.Y(n_17));
   INVX1 g1227 (.A(pp3[1]),
	.Y(n_16));
   DFFRXL \pp2_reg[0]  (.CK(clk),
	.D(n_2),
	.Q(pp2[0]),
	.QN(UNCONNECTED19),
	.RN(rst_n));
   DFFRX2 \pp2_reg[1]  (.CK(clk),
	.D(n_7),
	.Q(pp2[1]),
	.QN(UNCONNECTED20),
	.RN(rst_n));
   DFFRX2 \pp3_reg[0]  (.CK(clk),
	.D(n_11),
	.Q(pp3[0]),
	.QN(UNCONNECTED21),
	.RN(rst_n));
   DFFSRX1 \pp3_reg[1]  (.CK(clk),
	.D(n_5),
	.Q(pp3[1]),
	.QN(UNCONNECTED22),
	.RN(rst_n),
	.SN(1'b1));
   DFFRX2 \pp3_reg[3]  (.CK(clk),
	.D(n_1),
	.Q(pp3[3]),
	.QN(UNCONNECTED23),
	.RN(rst_n));
   DFFRX2 \pp1_reg[2]  (.CK(clk),
	.D(n_0),
	.Q(pp1[2]),
	.QN(UNCONNECTED24),
	.RN(rst_n));
   DFFRX2 \pp0_reg[1]  (.CK(clk),
	.D(n_10),
	.Q(pp0[1]),
	.QN(UNCONNECTED25),
	.RN(rst_n));
   DFFRX2 \pp3_reg[2]  (.CK(clk),
	.D(n_3),
	.Q(pp3[2]),
	.QN(UNCONNECTED26),
	.RN(rst_n));
   DFFRXL \pp0_reg[0]  (.CK(clk),
	.D(n_15),
	.Q(pp0[0]),
	.QN(UNCONNECTED27),
	.RN(rst_n));
   DFFRX2 \pp1_reg[0]  (.CK(clk),
	.D(n_9),
	.Q(pp1[0]),
	.QN(UNCONNECTED28),
	.RN(rst_n));
   DFFSRX1 \pp2_reg[2]  (.CK(clk),
	.D(n_4),
	.Q(pp2[2]),
	.QN(UNCONNECTED29),
	.RN(rst_n),
	.SN(1'b1));
   DFFRX2 \pp0_reg[3]  (.CK(clk),
	.D(n_8),
	.Q(pp0[3]),
	.QN(UNCONNECTED30),
	.RN(rst_n));
   DFFRX2 \pp0_reg[2]  (.CK(clk),
	.D(n_12),
	.Q(pp0[2]),
	.QN(UNCONNECTED31),
	.RN(rst_n));
   DFFRX2 \pp1_reg[3]  (.CK(clk),
	.D(n_6),
	.Q(pp1[3]),
	.QN(UNCONNECTED32),
	.RN(rst_n));
   DFFRX2 \pp1_reg[1]  (.CK(clk),
	.D(n_14),
	.Q(pp1[1]),
	.QN(UNCONNECTED33),
	.RN(rst_n));
   DFFRX2 \pp2_reg[3]  (.CK(clk),
	.D(n_13),
	.Q(pp2[3]),
	.QN(UNCONNECTED34),
	.RN(rst_n));
   AND2X1 g1239__5107 (.A(A[0]),
	.B(B[0]),
	.Y(n_15));
   AND2X1 g1236__6260 (.A(A[1]),
	.B(B[1]),
	.Y(n_14));
   AND2X1 g1237__4319 (.A(A[3]),
	.B(B[2]),
	.Y(n_13));
   AND2X1 g1238__8428 (.A(A[2]),
	.B(B[0]),
	.Y(n_12));
   AND2X1 g1246__5526 (.A(A[0]),
	.B(B[3]),
	.Y(n_11));
   AND2X1 g1240__6783 (.A(A[1]),
	.B(B[0]),
	.Y(n_10));
   AND2X1 g1241__3680 (.A(A[0]),
	.B(B[1]),
	.Y(n_9));
   AND2X1 g1242__1617 (.A(A[3]),
	.B(B[0]),
	.Y(n_8));
   AND2X1 g1248__2802 (.A(A[1]),
	.B(B[2]),
	.Y(n_7));
   AND2X1 g1244__1705 (.A(A[3]),
	.B(B[1]),
	.Y(n_6));
   AND2X1 g1245__5122 (.A(A[1]),
	.B(B[3]),
	.Y(n_5));
   AND2X1 g1247__8246 (.A(A[2]),
	.B(B[2]),
	.Y(n_4));
   AND2X1 g1243__7098 (.A(A[2]),
	.B(B[3]),
	.Y(n_3));
   AND2X1 g1249__6131 (.A(A[0]),
	.B(B[2]),
	.Y(n_2));
   AND2X1 g1251__1881 (.A(A[3]),
	.B(B[3]),
	.Y(n_1));
   AND2X1 g1250__5115 (.A(A[2]),
	.B(B[1]),
	.Y(n_0));
   CLKBUFXL drc_bufs1332 (.A(s1_b[3]),
	.Y(n_151));
   CLKBUFXL drc_bufs1372 (.A(s1_b[2]),
	.Y(n_195));
   CLKBUFXL drc_bufs1382 (.A(pp3[3]),
	.Y(n_206));
   CLKBUFXL drc_bufs1392 (.A(pp1[3]),
	.Y(n_217));
   CLKBUFXL drc_bufs1402 (.A(pp0[1]),
	.Y(n_228));
   CLKBUFXL drc_bufs1412 (.A(s1_a[2]),
	.Y(n_239));
   CLKBUFXL drc_bufs (.A(n_89),
	.Y(n_242));
   CLKBUFXL drc_bufs1425 (.A(n_60),
	.Y(n_253));
   CLKBUFXL drc_bufs1436 (.A(n_58),
	.Y(n_264));
   CLKBUFXL drc_bufs1453 (.A(n_68),
	.Y(n_281));
   CLKBUFXL drc_bufs1461 (.A(n_66),
	.Y(n_289));
   CLKBUFXL drc_bufs1472 (.A(n_80),
	.Y(n_300));
   CLKBUFXL drc_bufs1483 (.A(pp2[1]),
	.Y(n_311));
   CLKBUFXL drc_bufs1494 (.A(pp3[0]),
	.Y(n_322));
   CLKBUFX1 drc1594 (.A(n_217),
	.Y(n_425));
   CLKBUFX1 drc1602 (.A(n_206),
	.Y(n_433));
   CLKBUFX1 drc1606 (.A(n_253),
	.Y(n_437));
   CLKBUFX1 drc1610 (.A(n_228),
	.Y(n_441));
   CLKBUFX1 drc1614 (.A(n_264),
	.Y(n_445));
   AND2X1 g2 (.A(n_18),
	.B(n_35),
	.Y(n_450));
   NOR2BX1 g1619 (.AN(n_19),
	.B(n_38),
	.Y(n_451));
   AND2X1 g1620 (.A(n_52),
	.B(n_55),
	.Y(n_452));
endmodule

